# Generated by Django 5.2 on 2025-05-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('niveau_etudes', models.CharField(choices=[('BAC', 'Baccalauréat'), ('BAC+1', 'Bac+1'), ('BAC+2', 'Bac+2'), ('BAC+3', 'Bac+3'), ('BAC+4', 'Bac+4'), ('BAC+5', 'Bac+5')], max_length=5)),
                ('etablissement_origine', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('extrait_naissance', models.FileField(upload_to='documents/extraits/')),
                ('certificat', models.FileField(upload_to='documents/certificats/')),
                ('diplome', models.FileField(upload_to='documents/diplomes/')),
                ('lettre_motivation', models.FileField(upload_to='documents/lettres/')),
                ('photo', models.ImageField(upload_to='documents/photos/')),
                ('inscription_validee', models.BooleanField(default=False)),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforme.concours')),
            ],
        ),
    ]
